### ISSUE TITLE
Colored Status Bar on Debug

### ISSUE THREAD

**Issue by Reidond** [gistart/vscode-theme-desert-dawn#1]
How about colored status bar on debug that has color of `"activityBar.activeBorder": "#e95420"`, but darker or lighter version of it?

**Comment by gistart** [comment]
@Reidond I like it when it's always the same.

You can override it to any color you want via settings.json:

```
"workbench.colorCustomizations": {
    "statusBar.background" : "#123456",
    "statusBar.noFolderBackground" : "#789012",
    "statusBar.debuggingBackground": "#345678"
}
```

**Comment by Reidond** [comment]
Okay, I'll try that, thanks! 😊

**Comment by gistart** [comment]
@Reidond you don't need to fork and rebuild -- just edit your "global" settings.json, of vscode itself. https://code.visualstudio.com/api/references/theme-color
